config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'posts/index'

  get 'posts/new'

  get 'posts/create'

  get 'posts/edit'

  get 'posts/update'

  get 'posts/destroy'

  get 'cities/index'

  get 'cities/new'

  get 'cities/create'

  get 'cities/edit'

  get 'cities/update'

  get 'cities/destroy'
  

  devise_for :users
  get 'homes/index'
  root to: 'homes#index'

  resources :cities do
    resources :posts
  end

  resources :users do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :posts, dependent: :destroy

  

  has_attached_file :image, styles: { medium: '300x300>', large: '1024x400>', thumb: '100x100>' }, default_url: 'http://www.clipartkid.com/images/768/city-skyline-clip-art-item-4-vector-magz-free-download-vector-cIAVk5-clipart.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/join.rb
class Join < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :city, optional: true
  belongs_to :user, optional: true

  validates :title, length: { minimum: 2, maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    validates_uniqueness_of :username
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
    has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: 'http://i.imgur.com/2l9mUan.jpg'
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:city, :avatar, :username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  before_action :authenticate_user!

  def index
    @cities = City.all

  end

  def show
    city_id = params[:id]
    @city = City.find_by(id: city_id)
  end

  def new
    @city = City.new
  end

  def create
    city = City.new(city_params)

    if city.save
      redirect_to cities_index_path
    else
      flash[:error] = city.errors.full_messages.join(", ")
      redirect_to cities_new_path
    end
  end

  def edit
    city_id = params[:id]
    @city = City.find_by(id: city_id)
  end

  def update
    city_id = params[:id]
    city = City.find_by(id: city_id)

    if city.update(city_params)
      redirect_to city_path(city)
    else
      flash[:error] = city.errors.full_messages.join(", ")
      redirect_to edit_city_path(city)

    end
  end

  def destroy

    @city = City.delete
  end

  private
  def city_params
    params.require(:city).permit(:name, :address, :description, :longitude, :lattitude, :image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.all
    city_id = params[:city_id]
    @city = City.find_by(id: city_id)
    @post = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!

  def index
    city_id = params[:city_id]
    @city = City.find_by(id: city_id)


  end

  def show
    current_user
    post_id = params[:id]
    @post = Post.find_by(id: post_id)
  end

  def new
    @post = Post.new
    city_id = params[:city_id]
    @city = City.find_by(id: city_id)
    @user = current_user.id
  end

  def create

    city = City.find(params[:city_id])
    new_post = Post.new(post_params)
    new_post.user_id = current_user.id


  if new_post.save
      city.posts << new_post
      current_user.posts << new_post
      redirect_to city_posts_path(city, new_post)
  else
      flash[:error] = new_post.errors.full_messages.join(", ")
      redirect_to new_city_post_path(city)
  end

end

  def edit
    @user = current_user
    post_id = params[:id]
    @post = Post.find_by(id: post_id)
  end

  def update
    user = current_user
    post_id = params[:id]
    post = Post.find_by(id: post_id)

   if post.update(post_params)
     flash[:notice] = "Updated successfully."
     redirect_to homes_index_path(user, post)
   else
     flash[:error] = post.errors.full_messages.join(", ")
     redirect_to edit_user_post_path(user, post)
   end
 end


  def destroy
    post_id = params[:id]
    post = Post.find_by(id: post_id)
    post.delete

    user = current_user
    redirect_to homes_index_path(user)
  end


  private
  def post_params
   params.require(:post).permit(:text, :title)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applications/index.html.erb
<p>What's up</p>

app/views/cities/_form.html.erb
<%= form_for @city do |f| %>
<div class="field">
  <%= f.label :lattitude %>
  <%= f.text_field :lattitude, class: "form-control", placeholder: "lattitude" %>
</div>

<div class="field">
  <%= f.label :longitude %>
  <%= f.text_field :longitude, class: "form-control", placeholder: "longitude" %>
</div>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "City name" %>
</div>

<div class="field">
  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control", placeholder: "State" %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control", placeholder: "description" %>
</div>

<div class="field">
  <%= f.label :image %><br />
  <%= f.file_field :image %>
</div>

<div class="actions">
  <%= f.submit "Save City", class: "btn btn-block btn-success" %>
</div>
<% end %>

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<h1>Edit City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', homes_index_path %>

app/views/cities/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyBpoS8wBLRRkr2MGeRywG0E5_0tG3xV4cI"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<div class="city-clean">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="intro">
                  <h1> Here are the Current Tipsy Cities in the App</h1>
                  <hr>


                  <hr>
                  <div class="card-deck-wrapper">
                      <div class="card-deck">
                        <% @cities.each do |city| %>
                        <div class="card_city">
                          <img class="card-img-top" src="<%= city.image %>" alt="Card image cap">
                          <div class="card-block">
                            <h4 class="card-title"><%= city.name %></h4>
                            <p class="card-text"> <b>Description:</b> <%= city.description %></p>
                            <p class="card-text"><small class="text-muted"><button type="button" class="btn btn-default"><%= link_to "City and posts", city_path(city) %></small></button></p>
                          </div>
                        </div>
                        <% end %>
                      </div>
                    </div>





                </div>
            </div>
        </div>
    </div>
</div>


</script>

app/views/cities/new.html.erb
<h1>City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', homes_index_path %>

app/views/cities/show.html.erb
<header>
    <div class="city_image">
        <%= image_tag @city.image.url %>
    </div>
</header>

<div class="city-display">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="intro">

                    <h2>
                        <strong>City Name:
                        </strong><%= @city.name %>
                    </h2>
                    <hr>
                    <h2>
                      <strong>State:
                      </strong><%= @city.address %>

                    </h2>
                    <hr>
                    <h2>
                      <strong>Description:</strong>
                      <p><%= @city.description %></p>


                    </h2>

                    <hr/>
                    <div class="col-md-12">
                        <button type="button" class="btn btn-default"><%= link_to "Edit This City", edit_city_path(@city) %></button>
                        <button type="button" class="btn btn-default"><%= link_to "show post for this city", city_posts_path(@city) %></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/homes/index.html.erb
<% if current_user %>

  <div class="background_sign_in">
    <div class="container">
      <div class="row border">
        <div class="col-md-4">
          <div class="col-md-12">
            <%= image_tag current_user.avatar.url(:medium) %>
          </div>
          <div class="col-md-12" style="padding-top:20px;">
            <p>Username: <%= current_user.username %></p>
          </div>
          <div class="col-md-12">
            <p>Joined: <%= current_user.created_at.strftime("%m/%d/%Y") %></p>
          </div>
          <div class="col-md-12">
            <p>Current City:
            <%= current_user.city %></p>
          </div>
          <div class="col-md-4">
            <button type="button" class="btn btn-primary"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></button>
          </div>
          <div class="col-md-4">
            <button type="button" class="btn btn-success"><%= link_to 'Edit Profile.', edit_user_registration_path %></button>
          </div>
        </div>
        <div class="col-md-6" style="padding-left:10%">
          <div class="col-md-12">
            <h2>Posts:</h2>
          </div>
          <% current_user.posts.each do |post| %>
            <div class="col-md-12" style="padding-bottom:10px">
              <strong><%= link_to "Title: #{post.title}", user_post_path(current_user, post) %></strong>
              <p>
                <strong>City: <%= post.city.name %></strong>
                <br>
                Content: <%= post.text %>
              </p>
            </div>
          <% end %>
          <!-- <div class="col-md-12">
            <button type="button" class="btn btn-default"><%= link_to 'Show Cities', cities_index_path %></button>
          </div> -->
        </div>
      </div>
    </div>
  </div>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <!-- <title>TipsyTraveller</title> -->
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css', media: 'all' %>
        <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Cookie', media: 'all' %>
        <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Lora', media: 'all' %>
        <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css', media: 'all' %>
        <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700', media: 'all' %>
        <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700', media: 'all' %>
        <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css', media: 'all' %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js' %>
        <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js' %>
    </head>

    <body>
        <header>
            <nav id="margin-fix" class="navbar navbar-default">
                <div class="container">
                    <div class="navbar-header">
                        <a href="#" class="navbar-brand navbar-link">
                            <i class="icon ion-ios-wineglass"></i>
                            <span class="text-title">
                                Tipsy traveller!</span>
                        </a>
                        <button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggle collapsed">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="navcol-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li role="presentation"><%= link_to 'My Profile', '/homes/index' %></li>
                            <% if current_user %>
                           <li role="presentation"><%= link_to("Logout #{current_user.username}", destroy_user_session_path, :method => :delete) %></li>
                            <% else %>
                            <li role="presentation"><%= link_to 'Login', '/users/sign_in' %></li>
                            <li role="presentation"><%= link_to 'Signup', '/users/sign_up' %></li>
                            <% end %>

                        </ul>
                        <hr>

                    </div>
                </div>
            </nav>
        </header>
        <!-- <div class="nav_image">
        </div> -->
          <ul class="nav nav-pills categories">
              <li class="active"><%= link_to "View Cities", cities_path %></li>
          </ul>

          <%- flash.each do |name, msg| -%>
          <div class="alert alert-warning">
            <strong><%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %></strong>
          </div>
          <%- end -%>



        <!-- <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p> -->
        <!-- <h1>Tipsy Traveller</h1> -->
        <%= yield %>
    </body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@city, @post]  do |f| %>
<div class="form-group">
  <%= f.text_field :title, class: "form-control", placeholder: "Title ", required: true, autofocus: true %>
</div>

  <div class="form-group">
    <%= f.text_area :text, size: "24x6", class: "form-control", placeholder: "Post ", required: true %>
  </div>

  <div class="form-group">
    <%= f.submit "Save Post", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="form-index-clean">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="intro">
                  <h1>Edit Post</h1>
                  <%= form_for [@user, @post]  do |f| %>

                  <div class="form-group">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title ", required: true, autofocus: true %>
                  </div>

                    <div class="form-group">
                      <%= f.text_area :text, size: "24x6", class: "form-control", placeholder: "Post ", required: true %>
                    </div>

                    <div class="form-group">
                      <%= f.submit "Save Post", class: "btn btn-block btn-success" %>
                    </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="roster-display">

    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="intro">
                    <div class="show_header">
                        <h1>The Great city of
                            <%= @city.name %></h1>
                        <%= image_tag @city.image.url(:medium) %>

                    </div>

                    <ul class="nav nav-pills categories">
                        <li class="active"><button type="button" class="btn btn-default"><%= link_to "Create Post for #{@city.name}", new_city_post_path(@city) %></button></li>
                        <li><button type="button" class="btn btn-success"><%= link_to "Back to #{@city.name}", city_path(@city) %></button></li>
                    </ul>

                    <% @city.posts.reverse_each do |post| %>
                    <div class="card borders">
                        <img class="card-img-top" src="<%= post.user.avatar %>" alt="Card image cap">
                        <div class="card-block">
                            <h4 class="card-title">Title: <%= post.title %></h4>
                                <strong>Created by: <%= post.user.username %></strong>

                                <p class="posttime"><%= time_ago_in_words(post.created_at) %>
                                    Ago</p>
                                <p class="card-text">
                                  <b>Content:</b>  <%= post.text %>
                                </p>
                                <br>
                            </div>
                        </div>
                        <hr>
                        <% end %>

                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/posts/new.html.erb
<div class="form-index-clean">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="intro">
                  <h1>Add a Post to the City of <%= @city.name %></h1>
                  <%= render "form" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="card">
    <img class="card-img-top" src= "<%= @post.city.image %>" alt="Card image cap">
        <div class="card-block">
          <h4 class="card-title">City Name: <%= @post.city.name %></h4>
          <h4 class="card-title">Created By: <%= @post.user.username %></h4>
          <h4 class="card-title">Title: <%= @post.title %></h4>
          <p class="card-text"><b>Content:</b> <%= @post.text %></p>
          <br>
          <%= link_to 'Edit Post', edit_user_post_path(current_user, @post) %>
        <p><%= link_to "Delete this post", user_post_path(current_user, @post), data: {confirm: "Are you sure you want to delete this post: #{@post.title}"}, method: :delete %></p>
        </div>
      </div>
    <hr>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>